version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.20"
replacements:
  name: "DisguiseHeads"
  id: "disguiseheads"
  version: "1.0.1"
  relocationpackage: "dev.tr7zw.disguiseheads"
  modrinthid: "u4pgScAU"
  curseforgeid: "593611"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  DHFabric:
    template: "Fabric"
  DHForge:
    template: "Forge"