version: '0.0.2'
source: "https://github.com/tr7zw/ProcessedModTemplate/tree/master"
replacements:
  name: "DisguiseHeads"
  id: "disguiseheads"
  version: "1.2.2.1"
  description: "Swap skins when wearing a player head."
  homepageUrl: "https://modrinth.com/plugin/itemswapper"
  sourcesUrl: "https://github.com/tr7zw/DisguiseHeads"
  issuesUrl: "https://github.com/tr7zw/DisguiseHeads/issues"
  fabric_entrypoint: "dev.tr7zw.disguiseheads.DisguiseHeadsMod"
  fabric_modmenu_entrypoint: "dev.tr7zw.disguiseheads.config.DHModMenu"
  relocationpackage: "dev.tr7zw.disguiseheads"
  modrinthid: "u4pgScAU"
  curseforgeid: "593611"
  versionlessname: "DHVersionless"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
  - includeLibs
  - addTRenderLib
  - addTRansitionLib
rootProject:
  template: "."
subProjects:
  DHVersionless:
    template: "Versionless"
    replacements:
      dependencies: '
      compileOnly "com.google.code.gson:gson:2.10.1"

      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"
      '