# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[36,)"
license = "tr7zw Protective License"

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
issueTrackerURL="https://github.com/tr7zw/DisguiseHeads/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
modId = "disguiseheads"
version = "${version}"
displayName = "DisguiseHeads"
logoFile="icon.png" #optional
 authors="tr7zw" #optional
description = '''
Swap skins when wearing a player head.
'''

[[dependencies.disguiseheads]]
modId = "forge"
mandatory = true # do you **need** this mod to be able to launch?
versionRange = "[36,)" # This essentially means any forge >= 36
ordering = "NONE" # Use this if you want your mod to be loaded specifically BEFORE or AFTER another mod
side = "BOTH" # Specify where this mod is required: can be BOTH, CLIENT or SERVER

[[dependencies.disguiseheads]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
